
image: node:10.15.3

pipelines:
  branches:
    master: 
    - step:
        deployment: production
        caches:
          - node
        script:
          - npm install
          - npm run build
          - pipe: atlassian/ftp-deploy:0.3.2
            variables:
              USER: "$FTP_USERNAME"
              PASSWORD: "$FTP_PASSWORD"
              SERVER: $FTP_HOST
              REMOTE_PATH: /
              LOCAL_PATH: dist
