export const state = () => ({
  //el id 1 es los electronicos  y el aydi 2 lo demas 
  data: [{
      categoriaId: 1,
      id: 1,
      nombreCorto: 'Razer RZ07-02270100-R3U1',
      nombre: 'Razer RZ07-02270100-R3U1 Tartarus V2 Chroma - Ergonomic Mecha-Membrane Gaming Keypad - 32 Fully Programmable Keys - 8-Way Thumbpad & Scroll Wheel w/ Detachable Palm Rest.',
      src: '/img/teclados_gaming/Razer RZ07-02270100-R3U1.jpg',
      ref: 'https://amzn.to/2ZNDJfo',
      estrellas: 4.4,
    },
    {
      categoriaId: 1,
      id: 2,
      nombreCorto: 'HyperX Alloy Core RGB ',
      nombre: 'HyperX Alloy Core RGB – Teclado gamer español de membrana – Teclas silenciosas y rápidas con iluminación dinámica RGB, Resistente a derrames ,Compatible con Windows 10/8.1/8/7.',
      src: '/img/teclados_gaming/HyperX Alloy.jpg',
      ref: 'https://amzn.to/2zV4dAI',
      estrellas: 4.8,
    },
    {
      categoriaId: 1,
      id: 3,
      nombreCorto: 'Logitech G - G413',
      nombre: 'Logitech G - G413 - Teclado Mecánico con Iluminación para Gaming - Negro',
      src: '/img/teclados_gaming/logitecyh g.jpg',
      ref: 'https://amzn.to/2AInOEy',
      estrellas: 4.1,
    },
    {
      categoriaId: 1,
      id: 4,
      nombreCorto: 'Logitech G - G413',
      nombre: 'Logitech G213 Prodigy - Teclado Gaming, Retroiluminación RGB, Controles Multimedia, Negro (Teclado Inglés)',
      src: '/img/teclados_gaming/Logitech G213 Prodigy.jpg',
      ref: 'https://amzn.to/2WPl7cU',
      estrellas: 4.7,
    },
    {
      categoriaId: 1,
      id: 5,
      nombreCorto: 'GranVela ',
      nombre: 'GranVela MechanicalEagle Z-77 Multicolor Retroiluminada Juegos de Teclado Mecánico 87 Teclas [QWERTY US-Layout] con Azul Switches (Blanco)',
      src: '/img/teclados_gaming/GranVela MechanicalEagle Z-77.jpg',
      ref: 'https://amzn.to/3e78WOr',
      estrellas: 4.7,
    },
    {
      categoriaId: 1,
      id: 6,
      nombreCorto: 'Vorago Keyboard502',
      nombre: 'Vorago Keyboard502 Teclado Start The Game Alámbrico Metálico Multimedia Iluminado RGB USB, color Negro',
      src: '/img/teclados_gaming/Vorago Keyboard502.jpg',
      accesorios: '/img/accesorios/masvendidos.png',
      ref: 'https://amzn.to/3gdQTIa',
      estrellas: 4.6,
    },
    {
      categoriaId: 1,
      id: 7,
      nombreCorto: 'VicTsing',
      nombre: 'VicTsing Teclado Gaming Español USB Rainbow LED Retroiluminado con Ergonómico y Gran Durabilidad, Resistente a Derrames, Teclado con sensación mecánica (18.90inch)',
      src: '/img/teclados_gaming/VicTsing.jpg',
      ref: 'https://amzn.to/2LQb29A',
      estrellas: 3.9,
    },
    {
      categoriaId: 1,
      id: 8,
      nombreCorto: 'Razer Cynosa Chroma',
      nombre: 'Razer Cynosa Chroma - Teclado de juegos RGB multicolor - Teclas retroiluminadas individualmente - Diseño resistente a derrames - Razer Chroma',
      src: '/img/teclados_gaming/Razer Cynosa Chroma.jpg',
      ref: 'https://amzn.to/36m419R',
      estrellas: 4.6,
    },

    {
      categoriaId: 2,
      id: 9,
      nombreCorto: 'EagleTec KG011',
      nombre: 'EagleTec KG011 oficina/pegamento ultrafuerte LED retroiluminada teclado mecánico (blanco + plata)',
      src: '/img/teclados_mecanicos/EagleTec.jpg',
      ref: 'https://amzn.to/3c1kJfQ',
      estrellas: 4.3,
    },
    {
      categoriaId: 2,
      id: 10,
      nombreCorto: 'Asus ROG',
      nombre: `Asus ROG Teclado mecánico para Juegos Strix Flare Aura, COD Edición, Marrón Cherry MX, Cod Edition`,
      src: '/img/teclados_mecanicos/Asus ROG.jpg',
      ref: 'https://amzn.to/3bR73nG',
      estrellas: 4.4,
    },
    {
      categoriaId: 2,
      id: 11,
      nombreCorto: 'HyperX Alloy',
      nombre: `HyperX Alloy Core RGB – Teclado gamer español de membrana – Teclas silenciosas y rápidas con iluminación dinámica RGB, Resistente a derrames`,
      src: '/img/teclados_mecanicos/HyperX Alloy.jpg',
      ref: 'https://amzn.to/2LSbLa9',
      estrellas: 4.8,
    },
    {
      categoriaId: 2,
      id: 12,
      nombreCorto: 'HyperX Alloy Elite',
      nombre: `HyperX Alloy Elite RGB - Teclado mecánico para gaming - Cherry MX Red (Lineal) - Personalizable con el software HyperX NGENUITY - Descanso para muñeca - Retroiluminación RGB - Teclas Español Latam (HX-KB2RD2-LA/R2)`,
      src: '/img/teclados_mecanicos/HyperX Alloy Elite.jpg',
      ref: 'https://amzn.to/36ryzaf',
      estrellas: 4.6,
    },
    {
      categoriaId: 2,
      id: 13,
      nombreCorto: 'Drop ALT',
      nombre: `Drop ALT Teclado mecánico de alto perfil - 65% (67 llaves) teclado para juegos, interruptores de intercambio en caliente, macros programables, retroiluminación LED RGB, USB-C, Cherry MX Azul RGB, Gris`,
      src: '/img/teclados_mecanicos/Drop ALT.jpg',
      ref: 'https://amzn.to/3d0Zg80',
      estrellas: 4.4,
    },
    {
      categoriaId: 2,
      id: 13,
      nombreCorto: 'Razer RZ07-02270100-R3U1',
      nombre: `Razer RZ07-02270100-R3U1 Tartarus V2 Chroma - Ergonomic Mecha-Membrane Gaming Keypad - 32 Fully Programmable Keys - 8-Way Thumbpad & Scroll Wheel w/ Detachable Palm Rest`,
      src: '/img/teclados_mecanicos/Razer RZ07-02270100-R3U1.jpg',
      ref: 'https://amzn.to/2ZvkmYn',
      estrellas: 4.4,
    },
    {
      categoriaId: 2,
      id: 14,
      nombreCorto: 'Azio MK-RETRO-01',
      nombre: `Azio MK-RETRO-01 Teclado Mecánico Retro Inspirado en Máquina de Escribir`,
      src: '/img/teclados_mecanicos/Azio MK-RETRO-01.jpg',
      ref: 'https://amzn.to/3gl7zhk',
      estrellas: 4.3,
    },
    {
      categoriaId: 2,
      id: 15,
      nombreCorto: 'Azio MK-RETRO-L-03-US',
      nombre: `Azio MK-RETRO-L-03-US Teclado Mecánico Clásico Retro Usb, color Negro con Cobre`,
      src: '/img/teclados_mecanicos/Azio MK-RETRO-L-03-US.jpg',
      ref: 'https://amzn.to/2Tylbf6',
      estrellas: 4.2,
    },
    {
      categoriaId: 3,
      id: 16,
      nombreCorto: 'Logitech 920-008833',
      nombre: `Logitech 920-008833 Teclado inalambrico - USB + Bluetooth, QWERTY, Negro, Universal, Inalámbrico`,
      src: '/img/teclados_inalambricos/Logitech 920-008833.jpg',
      ref: 'https://amzn.to/3ec7kTF',
      estrellas: 4.8,
    },
    {
      categoriaId: 3,
      id: 17,
      nombreCorto: `Logitech - K480`,
      nombre: `Logitech - K480 - Teclado Inalámbrico Multidispositivo - Negro`,
      src: '/img/teclados_inalambricos/Logitech - K480.jpg',
      ref: 'https://amzn.to/2XlUZWo',
      estrellas: 4.7,
    },
    {
      categoriaId: 3,
      id: 18,
      nombreCorto: `CHOETECH Mini`,
      nombre: `Teclado Inalambrico,CHOETECH Mini Teclado Bluetooth Ultra-delgado Bluetooth 3.0 Conexión, Universal para iPhone/iPad Air/iPad Pro/iPad Mini, Windows, Smartphone y Tableta con Android 3.0 y Superior`,
      src: '/img/teclados_inalambricos/CHOETECH Mini.jpg',
      ref: 'https://amzn.to/2XpzqUQ',
      estrellas: 4.3,
    },
    {
      categoriaId: 3,
      id: 19,
      nombreCorto: `MTQ Combo `,
      nombre: `Teclado y Mouse Inalámbricos, MTQ Combo de Teclado y Mouse Inalámbricos,2.4G, Delgado Ergonómico ,3 Niveles de DPI Ajustables, Ideal para PC, Computadora Portátil, Computadora de Escritorio, Windows, Mac OS(Color Dorado)`,
      src: '/img/teclados_inalambricos/MTQ Combo.jpg',
      ref: 'https://amzn.to/2zoWyuA',
      estrellas: 3.6,
    },
    {
      categoriaId: 3,
      id: 20,
      nombreCorto: `TECHVIDA 2.4 GHz`,
      nombre: `TECHVIDA 2.4 GHz WiFi Ratón Inalámbrico Ergonómico Recargable 5 Botones USB Mouse Óptico Forma Vertical Wireless Protege el Brazo para Mac y Windows (Negro)`,
      src: '/img/teclados_inalambricos/TECHVIDA 2.4 GHz.jpg',
      ref: 'https://amzn.to/2TABaJP',
      estrellas: 4.4,
    },
    {
      categoriaId: 3,
      id: 21,
      nombreCorto: `Corsair Gaming K55 Teclado RGB`,
      nombre: `Corsair Gaming K55 Teclado RGB, Retroiluminación LED RGB, Inalámbrico, Negro`,
      src: '/img/teclados_inalambricos/Corsair Gaming K55 Teclado RGB.jpg',
      ref: 'https://amzn.to/36nNEtg',
      estrellas: 4.5,
    },
    {
      categoriaId: 3,
      id: 22,
      nombreCorto: `Arteck`,
      nombre: `Arteck - Teclado inalámbrico 2,4 G de acero inoxidable ultradelgado con teclado numérico para computadora/escritorio/PC/portátil/superficie/Smart TV y Windows 10/8/7 Batería recargable incorporada`,
      src: '/img/teclados_inalambricos/Arteck.jpg',
      ref: 'https://amzn.to/2TA61WG',
      estrellas: 4.4,
    },
    {
      categoriaId: 3,
      id: 23,
      nombreCorto: `HP Elite v2`,
      nombre: `HP Elite v2 - Teclado (RF inalámbrico, QWERTY, Inalámbrico, Negro, Monótono, 10 Metros)`,
      src: '/img/teclados_inalambricos/HP Elite v2.jpg',
      ref: 'https://amzn.to/36oMqhz',
      estrellas: 4.2,
    }, ,
    {
      categoriaId: 4,
      id: 24,
      nombreCorto: `Perixx`,
      nombre: `Perixx - Teclado Plegable Bluetooth, Negro`,
      src: '/img/teclados_bluetooth/Perixx.jpg',
      ref: 'https://amzn.to/2LTOqov',
      estrellas: 3.9,
    },
    {
      categoriaId: 4,
      id: 25,
      nombreCorto: `Microsoft All-in-One`,
      nombre: `Microsoft All-in-One Media Keyboard - Teclado (Estándar, Inalámbrico, RF inalámbrico, QWERTY, Negro)`,
      src: '/img/teclados_bluetooth/Microsoft All-in-One.jpg',
      ref: 'https://amzn.to/2ZwCZLx',
      estrellas: 4,
    },
    {
      categoriaId: 4,
      id: 26,
      nombreCorto: `Logitech - K400 Plus`,
      nombre: `Logitech - K400 Plus - Teclado Inalámbrico con Pad - Gris`,
      src: '/img/teclados_bluetooth/Logitech - K400 Plus.jpg',
      ref: 'https://amzn.to/3gk7ZnS',
      estrellas: 4.4,
    },
    {
      categoriaId: 4,
      id: 27,
      nombreCorto: `Logitech Bluetooth Multi-Device`,
      nombre: `
      Logitech Bluetooth Multi-Device Keyboard K480 – Black – works with Windows and Mac Computers, Android and iOS Tablets and Smartphones`,
      src: '/img/teclados_bluetooth/Logitech Bluetooth Multi-Device.jpg',
      ref: 'https://amzn.to/2LX6yhn',
      estrellas: 4.2,
    },
    {
      categoriaId: 4,
      id: 28,
      nombreCorto: `JETech 2156-KB-BT-UNIVERSAL-WH`,
      nombre: `JETech 2156-KB-BT-UNIVERSAL-WH - Teclado (Mini, Inalámbrico, Bluetooth, Interruptor mecánico, Blanco)`,
      src: '/img/teclados_bluetooth/JETech 2156-KB-BT-UNIVERSAL-WH.jpg',
      ref: 'https://amzn.to/3d2lOWe',
      estrellas: 3.8,
    },
    {
      categoriaId: 4,
      id: 30,
      nombreCorto: `Portátil BT`,
      nombre: `Teclado plegable inalámbrico con Bluetooth portátil BT y recargable Jelly Comb. Con pantalla táctil para tableta Samsung y celulares., Gris oscuro`,
      src: '/img/teclados_bluetooth/portatil BT.jpg',
      ref: 'https://amzn.to/2WZTWwd',
      estrellas: 4,
    },
    {
      categoriaId: 4,
      id: 31,
      nombreCorto: `WeChip Mini Air Mouse`,
      nombre: `WeChip Mini Air Mouse, 2018 Newest 2.4G Smart TV Wireless Fly Mouse Keyboard W1 Multifunctional Infrared Remote Control for Android TV Box/PC/Smart TV/Projector/HTPC/All-in-One PC/TV`,
      src: '/img/teclados_bluetooth/WeChip Mini Air Mouse.jpg',
      ref: 'https://amzn.to/3eehbbx',
      estrellas: 4,
    },
    {
      categoriaId: 4,
      id: 32,
      nombreCorto: `iClever Wireless Folding`,
      nombre: `iClever Wireless Folding Keyboard with 3-Color Backlight, Tri-Folding Bluetooth Keyboard with Aluminum Alloy Base for iOS Windows Android Tablets, Smartphones, Laptops, PC and More`,
      src: '/img/teclados_bluetooth/iClever Wireless Folding.jpg',
      ref: 'https://amzn.to/3cXw9CA',
      estrellas: 4.3,
    },
    {
      categoriaId: 5,
      id: 33,
      nombreCorto: `Corsair Gaming K55`,
      nombre: `Corsair Gaming K55 Teclado RGB, Retroiluminación LED RGB, con Cable + Mouse`,
      src: '/img/teclados_mouse/Corsair Gaming K55.jpg',
      ref: 'https://amzn.to/3cUoN2N',
      estrellas: 4.5,
    },
    {
      categoriaId: 5,
      id: 34,
      nombreCorto: `Logitech Desktop MK120`,
      nombre: `Logitech Desktop MK120 Durable, Comfortable, USB Mouse and keyboard Combo`,
      src: '/img/teclados_mouse/Logitech Desktop MK120.jpg',
      ref: 'https://amzn.to/36s2oaP',
      estrellas: 4.5,
    },
    {
      categoriaId: 5,
      id: 35,
      nombreCorto: `Dell 5wh32`,
      nombre: `Teclado Inalámbrico Y Mouse Dell 5wh32 Baterías Incluidas`,
      src: '/img/teclados_mouse/Dell 5wh32.jpg',
      ref: 'https://amzn.to/2LVS816',
      estrellas: 4.1,
    },
    {
      categoriaId: 5,
      id: 36,
      nombreCorto: `BlueFinger`,
      nombre: `BlueFinger - Teclado y Mouse para Juegos con Cable USB con retroiluminación y Teclado Combinados, Teclado y Mouse para Juegos, Gaming Keyboard Mouse Blue Headset Combo USB Óptico 800DPI Azul Mouse`,
      src: '/img/teclados_mouse/BlueFinger.jpg',
      ref: 'https://amzn.to/3eje3eJ',
      estrellas: 4.2,
    },

    {
      categoriaId: 5,
      id: 37,
      nombreCorto: `EagleTec Wireless`,
      nombre: `EagleTec Wireless Keyboard and Mouse Combo for PC, Computer and Small Portable Ergonomic Cordless Computer Mouse with 104 Keys Wireless Keyboard with Mini USB Receiver (K104 Black Version)`,
      src: '/img/teclados_mouse/EagleTec Wireless.jpg',
      ref: 'https://amzn.to/3bVlSpn',
      estrellas: 4.5,
    },
    {
      categoriaId: 5,
      id: 39,
      nombreCorto: `18 x 5.6 pulgadas (LxW)`,
      nombre: `Bring sleek design and consistency to your desktop with the wired keyboard and mouse bundle from AmazonBasics.`,
      src: '/img/teclados_mouse/18 x 5.6 pulgadas (LxW).jpg',
      ref: 'https://amzn.to/3bZyfRl',
      estrellas: 4.4,
    },
    {
      categoriaId: 5,
      id: 40,
      nombreCorto: `JOYACCESS`,
      nombre: `Bring sleek design and consistency to your desktop with the wired keyboard and mouse bundle from AmazonBasics.`,
      src: '/img/teclados_mouse/JOYACCESS.jpg',
      ref: 'https://amzn.to/3bZyfRl',
      estrellas: 4.4,
    },
    {
      categoriaId: 5,
      id: 41,
      nombreCorto: `Combo Mk520 `,
      nombre: `Logitech Wireless Combo Mk520 con teclado y mouse`,
      src: '/img/teclados_mouse/Combo Mk520.jpg',
      ref: 'https://amzn.to/3d0uRa7',
      estrellas: 4.5,
    },
    {
      categoriaId: 6,
      id: 42,
      nombreCorto: `MOSISO Funda `,
      nombre: `MOSISO Funda Dura Compatible con MacBook Pro 13 Retina A1502 / A1425 (Versión 2015/2014/2013/fin 2012), Carcasa Rígido & Cubierta de Teclado (USA Versión) & Protector de Pantalla, Marsala Rojo`,
      src: '/img/teclados_fundas/MOSISO Funda.jpg',
      ref: 'https://amzn.to/2yre1C2',
      estrellas: 4.3,
    },
    {
      categoriaId: 6,
      id: 43,
      nombreCorto: `laptops de 14 `,
      nombre: `AmazonBasics Funda protectora para laptops de 14"`,
      src: '/img/teclados_fundas/Funda protectora para laptops.jpg',
      ref: 'https://amzn.to/2WX78Sm',
      estrellas: 4.7,
    },
    {
      categoriaId: 6,
      id: 44,
      nombreCorto: `JETech `,
      nombre: `JETech Funda Portátil Compatible 15,4" Notebook Tableta iPad Tab, Función Protectora Impermeable Resistente a Golpes con el Bolsillo del Accesorio`,
      src: '/img/teclados_fundas/JETech.jpg',
      ref: 'https://amzn.to/2TPvxaT',
      estrellas: 4.8,
    },
    {
      categoriaId: 6,
      id: 44,
      nombreCorto: `Bolsa Blanda de Neopreno`,
      nombre: `MOSISO Funda Protectora Compatible con 2019 2018 MacBook Air 13 A1932 Retina/2019-2016 MacBook Pro 13 A2159 A1989 A1706 A1708, Bolsa Blanda de Neopreno Agua Repelente con Pequeño Caso, Vino Rojo`,
      src: '/img/teclados_fundas/Bolsa Blanda de Neopreno.jpg',
      ref: 'https://amzn.to/3bYGH31',
      estrellas: 4.7,
    },
    {
      categoriaId: 6,
      id: 44,
      nombreCorto: ` HP Envy x360 2 en 1 15.6 `,
      nombre: `Funda de teclado para HP Envy x360 2 en 1 15.6" Laptop Series / 2018 más reciente HP Pavilion 15.6 pulgadas Series / 2018 HP Envy 17.3" 17M 17-BS 17-BW Series Funda Protectora Negro, Negro`,
      src: '/img/teclados_fundas/HP Envy x360 2 en 1 15.6.jpg',
      ref: 'https://amzn.to/3gh2cQ0',
      estrellas: 4.4,
    },
    {
      categoriaId: 6,
      id: 44,
      nombreCorto: `MacBook Pro 13 A2159 `,
      nombre: `MOSISO Funda Dura Compatible con 2019 2018 2017 2016 MacBook Pro 13 A2159 A1989 A1706 A1708, Carcasa de Plástico & Cubierta de Teclado (USA Versión) & Protector de Pantalla, Mármol de Ola Creativo`,
      src: '/img/teclados_fundas/MacBook Pro 13 A2159.jpg',
      ref: 'https://amzn.to/2XlBpJI',
      estrellas: 4.2,
    },
    {
      categoriaId: 6,
      nombreCorto: ` MacBook Air 13 `,
      nombre: `MOSISO Funda Dura Compatible con MacBook Air 13 (A1369/A1466, Versión 2010-2017), Plástico Carcasa Rígida de Patrón & Cubierta de Teclado (USA Versión) & Protector de Pantalla, Peonía`,
      src: '/img/teclados_fundas/MacBook Air 13.jpg',
      ref: 'https://amzn.to/2M7yTBP',
      estrellas: 4.5,
    },
    {
      categoriaId: 6,
      nombreCorto: ` Mac Book 2010-2017`,
      nombre: `Lenfech Cubre Teclado para MacBook 2012-2015 Pro 13 y 15, Air 13/ Retina 15 y Mac Book 2010-2017 Air 13. Protector de Teclado en Español de Silicón. Protege de Líquidos y Polvo (Azul Degradado)`,
      src: '/img/teclados_fundas/Mac Book 2010-2017.jpg',
      ref: 'https://amzn.to/2Tz9sgC',
      estrellas: 4.6,
    },
    {
      categoriaId: 7,
      nombreCorto: `Alesis Melody 61 MKII`,
      nombre: `Alesis Melody 61 MKII - 61-Key Portable Keyboard with Built-In Speakers, Headphones, Microphone, Piano Stand, Music Rest and Stool`,
      src: '/img/teclados_piano/Alesis Melody 61 MKII.jpg',
      ref: 'https://amzn.to/2zhrsoQ',
      estrellas: 4.4,
    },
    {
      categoriaId: 7,
      nombreCorto: `RockJam`,
      nombre: `RockJam Teclado Eléctrico con Soporte, Taburete, Pedal y Audífonos`,
      src: '/img/teclados_piano/RockJam.jpg',
      ref: 'https://amzn.to/36tXytj',
      estrellas: 4.4,
    },
    {
      categoriaId: 7,
      nombreCorto: `Alesis Recital`,
      nombre: `Alesis Recital - Piano digital de 88 teclas para principiantes, Considerando 61`,
      src: '/img/teclados_piano/Alesis Recital.jpg',
      ref: 'https://amzn.to/3cUUtFf',
      estrellas: 4.4,
    },
    {
      categoriaId: 7,
      nombreCorto: `Casio SA-76`,
      nombre: `Casio SA-76 Teclado con 44 Teclas Mini, 100 Tonos, 50 Ritmos, 10 Melodías, color Negro`,
      src: '/img/teclados_piano/Casio SA-76.jpg',
      ref: 'https://amzn.to/3eiEq4y',
      estrellas: 4.2,
    },
    {
      categoriaId: 7,
      nombreCorto: `Alesis V49`,
      nombre: `Alesis V49 Teclado Controlador 49 Teclas`,
      src: '/img/teclados_piano/Alesis V49.jpg',
      ref: 'https://amzn.to/3eduSrm',
      estrellas: 4.5,
    },
    {
      categoriaId: 7,
      nombreCorto: `Midiplus AKM320`,
      nombre: `Midiplus AKM320 Controlador MIDI de 32 teclas, Teclado, 32-Key`,
      src: '/img/teclados_piano/Midiplus AKM320.jpg',
      ref: 'https://amzn.to/3eiTGOP',
      estrellas: 4.1,
    },
    {
      categoriaId: 7,
      nombreCorto: `Suzuki MDG-300-BL`,
      nombre: `Suzuki MDG-300-BL - Piano digital (88 teclas)`,
      src: '/img/teclados_piano/Suzuki MDG-300-BL.jpg',
      ref: 'https://amzn.to/2ZBG3Gb',
      estrellas: 3.4,
    },
    {
      categoriaId: 7,
      nombreCorto: `Yamaha PSR-E263`,
      nombre: ` Yamaha PSR-E263 61-Key Portable Keyboard`,
      src: '/img/teclados_piano/Yamaha PSR-E263.jpg',
      ref: 'https://amzn.to/2Tun5xt',
      estrellas: 4.5,
    },
    {
      categoriaId: 8,
      nombreCorto: `HyperX Cloud`,
      nombre: ` 
      HyperX Cloud II Audífonos para gaming, Color Rojo, 7.1 Surround Sound, compatible con PC, PS4, PS4 PRO, Xbox One, Xbox One S (KHX-HSCP-RD)`,
      src: '/img/audifonos/HyperX Cloud.jpg',
      ref: 'https://amzn.to/3gfnGNc',
      estrellas: 4.7,
    },
    {
      categoriaId: 8,
      nombreCorto: `Sennheiser HD 206`,
      nombre: `Sennheiser HD 206 Audífonos supraaurales, Negro/Plata`,
      src: '/img/audifonos/Sennheiser HD 206.jpg',
      ref: 'https://amzn.to/2TDrvCi',
      estrellas: 4.4,
    },
    {
      categoriaId: 8,
      nombreCorto: `Panasonic RP-HJE120-K`,
      nombre: `Panasonic RP-HJE120-K In-ear Negro`,
      src: '/img/audifonos/Panasonic RP-HJE120-K.jpg',
      ref: 'https://amzn.to/2XrCi3y',
      estrellas: 4.3,
    },
    {
      categoriaId: 8,
      nombreCorto: `Xiaomi`,
      nombre: `Xiaomi Audífonos Redmi Airdots`,
      src: '/img/audifonos/Xiaomi.jpg',
      ref: 'https://amzn.to/2XmcHZI',
      estrellas: 4.3,
    },
    {
      categoriaId: 8,
      nombreCorto: `Bose`,
      nombre: `Bose, Audífonos de Conectividad Inalámbrica In-ear, 761529-0020, Azul`,
      src: '/img/audifonos/Bose.jpg',
      ref: 'https://amzn.to/3ecGCdC',
      estrellas: 4.4,
    },
    {
      categoriaId: 8,
      nombreCorto: `Apple AirPods`,
      nombre: `Apple AirPods with Charging Case (Latest Model)`,
      src: '/img/audifonos/Apple AirPods.jpg',
      ref: 'https://amzn.to/2XoBiNr',
      estrellas: 4.6,
    },
    {
      categoriaId: 8,
      nombreCorto: `Apple MMTN2AM/A`,
      nombre: `Apple MMTN2AM/A Adaptador Earpods Lightning Connect, Color Blanco`,
      src: '/img/audifonos/Apple MMTN2AM.jpg',
      ref: 'https://amzn.to/2ZxFsp6',
      estrellas: 4.4,
    },
    {
      categoriaId: 8,
      nombreCorto: `SAMSUNG Galaxy Buds`,
      nombre: `SAMSUNG Galaxy Buds, audífonos inalámbricos con Bluetooth (Funda de Carga inalámbrica incluida), Color Negro`,
      src: '/img/audifonos/SAMSUNG Galaxy Buds.jpg',
      ref: 'https://amzn.to/2TwZyf5',
      estrellas: 4.3,
    },
    {
      categoriaId: 9,
      nombreCorto: `Lenovo Legion Y530`,
      nombre: `Lenovo Legion Y530-15ICH Notebook_Computer,Bluetooth+ Wi-Fi,15.6inches,Intel Core_i5 2.4GHz,16GB,DDR3,1000GB,Windows 10,Negro`,
      src: '/img/laptops_gaming/Lenovo Legion Y530.jpg',
      ref: 'https://amzn.to/2yzi8fA',
      estrellas: 3.7,
    },
    {
      categoriaId: 9,
      nombreCorto: `MSI Gaming GL62M 7REX`,
      nombre: `MSI Gaming GL62M 7REX-1896US computadora portátil Negro 39.6 cm (15.6") 1920 x 1080 Pixeles 2.8 GHz Intel® Core™ i7 de la séptima generación i7-7700HQ - Ordenador portátil (Intel® Core™ i7 de la séptima generación, 2.8 GHz, 39.6 cm (15.6"), 1920 x 1080 Pixeles, 8 GB, 1128 GB)`,
      src: '/img/laptops_gaming/MSI Gaming GL62M 7REX.jpg',
      ref: 'https://amzn.to/36sme5v',
      estrellas: 3.9,
    },
    {
      categoriaId: 9,
      nombreCorto: `Acer Spin 3 Convertible`,
      nombre: `Acer Spin 3 Convertible Laptop, 14" Full HD IPS Touch, 8th Gen Intel Core i7-8565U, 16GB DDR4, 512GB PCIe NVMe SSD, Backlit KB, Fingerprint Reader, Rechargeable Active Stylus, SP314-53N-77AJ`,
      src: '/img/laptops_gaming/Acer Spin 3 Convertible.jpg',
      ref: 'https://amzn.to/3cVziTs',
      estrellas: 4.3,
    },
    {
      categoriaId: 9,
      nombreCorto: `ASUS ROG Zephyrus S`,
      nombre: `ASUS ROG Zephyrus S Laptop PC ultradelgada para gaming, GTX 1070 | 512G SSD, Negro, 15-15.99 inches`,
      src: '/img/laptops_gaming/ASUS ROG Zephyrus S.jpg',
      ref: 'https://amzn.to/2LSBEXt',
      estrellas: 4.1,
    },
    {
      categoriaId: 9,
      nombreCorto: `Acer E5-576-392H Aspire E`,
      nombre: `Acer E5-576-392H Aspire E 15 Laptop Full HD, 8º Gen Intel Core i3-8130U, 6GB de memoria RAM, 1TB HDD, 8X DVD, Negro obsidiana, 15.6 pulgadas [Teclado ingles]`,
      src: '/img/laptops_gaming/Acer E5-576-392H Aspire E.jpg',
      ref: 'https://amzn.to/36pSaaQ',
      estrellas: 4.2,
    },
    {
      categoriaId: 9,
      nombreCorto: `Acer Predator Helios 300`,
      nombre: `Acer Predator Helios 300 Laptop para Juegos, Portátil , Negro, i7-8750 w/ 144Hz`,
      src: '/img/laptops_gaming/Acer Predator Helios 300.jpg',
      ref: 'https://amzn.to/2yziVx4',
      estrellas: 4.1,
    },
    {
      categoriaId: 9,
      nombreCorto: `Asus VivoBook 15 `,
      nombre: `Asus VivoBook 15 - Laptop Delgada y Ligera, 15.6 Pulgadas, Full HD, AMD Quad Core R5-3500U, 8GB DDR4 RAM, 256GB PCIe SSD, AMD Radeon Vega 8 Graphics, Windows 10 Home, F512DA-EB51, Color Gris`,
      src: '/img/laptops_gaming/Asus VivoBook 15.jpg',
      ref: 'https://amzn.to/2AZwSFp',
      estrellas: 4.1,
    },
    {
      categoriaId: 9,
      nombreCorto: `Area 51M Gaming `,
      nombre: `Area 51M Gaming Laptop Welcome to A New ERA with 9TH Gen Intel Core I9-9900 NVIDIA GEFORCE RTX 2080 8GB GDDR6 17.3" FHD 144HZ AG IPS NVIDIA G-Sync TOBII EYETRACKING (2TB SSD Raid|128GB RAM|10 Pro)`,
      src: '/img/laptops_gaming/Area 51M Gaming.jpg',
      ref: 'https://amzn.to/2LXndRW',
      estrellas: 5.5,
    },
  ],
})
